name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

env:
  CI: true
  PYTHON_VERSION: "3.12"

jobs:
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Publicar documentação
        run: mkdocs gh-deploy --force